# todo se puede ver la en documentacion de git

name: firts-worflow 
# on: push
# # se puede configurar varios on de la siguiente forma [push,workflow_dispatch,...]
on:
  pull_request: 
    types: 
      - opened
    branches: 
      - main
      - 'dev-*' # dev-new dev-this-is-new -> como se utilizan los slashes y los asteriscos
      - 'feat/**' # feat/new feat/this/new -> nos permite realizar mas de un slash en la ruta de la rama
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'dev-*' # dev-new dev-this-is-new -> como se utilizan los slashes y los asteriscos
      - 'feat/**' # feat/new feat/this/new -> nos permite realizar mas de un slash en la ruta de la rama
    # paths-ignore:
    #   - '.github/workflows/*'
# otra forma de hacer los on - es mas compleja pero permite especificar diferentes tipos mira el ejemplo de arriba
jobs:
  fibonacci:
    runs-on: ubuntu-latest #obligatorio para todos los jobs que se creen
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Dependencies
        run: pip install -r ./requirements.txt
      - name: Run Test
        run: pytest ./fibonacci
  
  django-test:
    runs-on: ubuntu-latest
    needs: fibonacci
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Dependencies
        run: pip install -r ./requirements.txt
      - name: Run Test
        run: pytest ./api
      
  deploy:
    needs: [fibonacci,django-test] # para decirle que necesita que termine primero este antes de seguir la ejecucion de este
    #para decirle que necesita de varios jobs se hace [test,test.,..]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Dependencies
        run: echo "instalando dependencia"
      - name: Deploying
        run: echo "deploy"

